### ISSUE TITLE
无法正确获取bangumi信息

### ISSUE THREAD

**Issue by 2lifetop** [TensoRaws/yuisub#11]
bangumi存在内版，无法直接调用API或者未登录状态进行查询，然后会陷入无限尝试中

**Comment by 2lifetop** [comment]
api 调试地址 ：https://bangumi.github.io/api/
建议加上Access Token选项

**Comment by Tohrusky** [comment]
> bangumi存在内版，无法直接调用API或者未登录状态进行查询，然后会陷入无限尝试中

内站是里番吗（

**Comment by Tohrusky** [comment]
> api 调试地址 ：[bangumi.github.io/api](https://bangumi.github.io/api/) 建议加上Access Token选项

草 原来给了接口啊 现在写的是嗯爬的

**Comment by NULL204** [comment]
现在有一个问题就是，API获取characters只有日文，没有中文
只有 https://api.bgm.tv/v0/characters/{character_id} 才会有中文名
所以在获取角色id后大量循环获取中文名效率会低到令人发指
尝试使用 asyncio aiohttp 后会报403错误

**Comment by 2lifetop** [comment]
效率应该还行，基本上只有curl的时间，对于翻译字幕这种场景这点效率损失应该能承受。

**Comment by Tohrusky** [comment]
现在的试试看呢

**Comment by Tohrusky** [comment]
v1.2.0 has been released
